version: "3.7"

services:
    app: 
        build:
            context: ./app
            dockerfile: Dockerfile
        image: serbanblebea/name-search-engine-app:latest
        container_name: app
        volumes:
            - ./app:/app
        networks:
            - app-network
        depends_on:
            - db
            - redis
            - seeder
        restart: on-failure
    nginx:
        build: ./nginx
        image: serbanblebea/name-search-engine-nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./app:/app
        networks:
            - app-network
        depends_on:
            - app
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
            interval: 2m30s
            timeout: 10s
            retries: 3
            start_period: 20s
    db:
        image: mariadb:latest
        container_name: db
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pass
        ports:
            - 3306:3306
        networks:
            - app-network
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - app-network
    seeder:
        build: 
            context: ./app
            dockerfile: Dockerfile
        image: serbanblebea/name-search-engine-app:latest
        entrypoint: php seed.php
        container_name: seeder
        networks: 
            - app-network
        depends_on:
            - db
        restart: on-failure

networks:
    app-network:
        driver: bridge
